# Site settings
title: Adam Phillip-Silver
email: your-email@domain.com
description: "A homepage for me"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
